spring:
  application:
    name: sistemaveterinario

  datasource:
    url: jdbc:mysql://localhost:3306/sistemavet?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update